name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Check for outdated packages
      run: npm outdated || true

    - name: Update dependencies
      run: |
        npm update
        npm audit fix --audit-level moderate || true

    - name: Test after updates
      run: |
        npm run lint
        npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update npm dependencies'
        title: '🔄 Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates

          This PR contains automated updates to npm dependencies:

          - Updated outdated packages to latest compatible versions
          - Ran security audit fixes for moderate+ vulnerabilities
          - Verified linting and build process still work

          Please review the changes and merge if all checks pass.

          🤖 Generated automatically by GitHub Actions
        branch: dependency-updates
        delete-branch: true
